version: '3.9'
services:
  db:
    image: mysql
    volumes:
      - "dbdata:/var/lib/mysql"
    container_name: db
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
       - MYSQL_ROOT_PASSWORD=sysgerfin
       - MYSQL_DATABASE=sysgerfin
       - MYSQL_USER=user_sysgerfin
       - MYSQL_PASSWORD=sysgerfin@123
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      start_period: 60s
    ports:
      - 3306:3306
    networks: 
      - sistema-network 
  backend:
    build: .
    container_name: GERENCIAMENTO-FINANCEIRO-SERVICE
    restart: on-failure    
    ports:
      - 8080:8080
    environment: 
      - DATABASE_HOST=db  
      - DATABASE_USER=user_sysgerfin
      - DATABASE_NAME=sysgerfin
      - DATABASE_PORT=3306
    networks:
      - sistema-network
networks:
  sistema-network:
    driver: bridge
volumes:
  dbdata: 