server:
  port: 8080
spring:
  application:
    name: GERENCIAMENTO-FINANCEIRO-SERVICE
  datasource:
#    url: jdbc:h2:mem:GerenciamentoFinanceiro
    url: jdbc:mysql://db:3306/sysgerfin?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user_sysgerfin
    password: sysgerfin@123
  jpa:
    properties:
       hibernate.format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
#  h2:
#    console:
#      enabled: true
